= Pirátská infrastruktura: Technická specifikace
Jan Hamal Dvořák <jan.hamal.dvorak@pirati.cz>; Miroslav Brabenec <brabemi@gmail.com>; Jitka Novotná <jitka.novotna@pirati.cz>
:numbered:
:icons: font
:lang: cs
:table-caption: Tabulka
:note-caption: Poznámka
:warning-caption: Pozor
:example-caption: Schéma
:toc-title: Obsah
:toc: left

:y: icon:check[role="green"]
:n: icon:times[role="red"]


WARNING: Tento dokument je rozpracovaný, neúplný a neprošel řádnou oponenturou mimo kolektiv jeho autorů. Pokud se jím budete řídit, činíte tak na vlastní nebezpečí. Pro podrobnosti kontaktujte Jana Hamala Dvořáka na jeho Pirátském emailu nebo telefonicky na čísle 723{nbsp}671{nbsp}732.


<<<

== Identity

=== Základní pohled

.Tok informací o identitách (obecně)
====
[plantuml,align="center"]
....
@startuml
left to right direction

database LDAP
component Keycloak

package "Obslužné systémy" {
  package Nalodění {
  }

  package People {
  }
}

package "Koncový systém" {
  component httpd
  component Aplikace
  database DB

  Aplikace <-l-> DB
  httpd <-l-> Aplikace

  httpd <-u- Keycloak: "SSO, tj. zjištění identity"
}

component IdM

DB <-u- IdM
IdM <-u- LDAP

Keycloak <-r-> LDAP
Nalodění <-d-> LDAP
People <-d-> LDAP

@enduml
....
====

LDAP::
LDAP je zdrojem autoritativních informací o identitách. Do LDAPu zapisují pouze obslužné systémy jako Nalodění, People a také Keycloak SSO. Koncové systémy získávají data z LDAPu v rozsahu nutném pro svůj provoz prostřednictvím průběžné replikace s transformací.

Keycloak::
Keycloak poskytuje SSO (Single Sign-On), tedy jednotné přihlášení do ostatních systémů. Jako úložiště informací o uživatelích využívá právě LDAP. Z technických důvodů také umožňuje omezenou správu uživatelských účtů.

IdM::
Systém správy identit má zajišťovat přenos informací z autoritativního zdroje (LDAPu) do koncových systémů. Aktuálně je realizován jako dílčí aplikace, které přistupují do LDAPu s omezenými právy a průběžně replikují potřebné údaje do lokálních databází.

Koncový systém::
Z pohledu správy identit je koncový systém takový, který pouze čerpá informace z autoritativní databáze (LDAPu) a případně využívá jednotné přihlašování přes Keycloak, avšak sám již do LDAPu žádné údaje nezanáší.

Obslužné systémy::
Systémy **Nalodění** a **People** umožňují správu uživatelských účtů. Nalodění je samoobslužným systémem členů, People slouží především stranickému aparátu.


<<<

=== Obslužné systémy

.Tok informací o identitách (obslužné systémy)
====
[plantuml,align="center"]
....
@startuml
left to right direction

database LDAP

package Nalodění {
}

package People {
}

package Ostatní {
}

Nalodění <-d-> LDAP
People <-d-> LDAP
LDAP -d-> Ostatní

:Každý: -d- Nalodění
:Pověřené osoby \n (AO / PO): -d- People
@enduml
....
====

Nalodění::
Systém Nalodění je určen všem uživatelům, kteří v něm mohou samoobslužně měnit údaje o sobě, měnit si způsob autentizace a požádat o odstranění ze systémů strany. Také zde mohou získat kompletní výpis dat, která o nich strana vede.

People::
Systém People slouží především odborům Administrativnímu a Personálnímu, které v něm spravují informace o uživatelích jednak vyplývající ze stanov (například je-li někdo zvolen, je potřeba to zavést do systému), ale také například informace o dobrovolnících. V tomto ohledu pak plní systém People roli podobnou CRM.


<<<

== LDAP

=== Schéma

.DN pro jednotlivé typy objektů
[options="header",cols="<1,<3"]
|===
| DN
| Typ objektů

| `OU=People,O=Pirati`
| Uživatelské účty

| `OU=Groups,O=Pirati`
| Skupiny uživatelů

| `OU=Systems,O=Pirati`
| Systémové účty přistupující do LDAPu
|===


==== OU=People,O=Pirati

Aktuálně je jediný úplný uživatelský kmen ve fóru na platformě **phpBB**, proto jej budeme při migraci brát jako autoritativní zdroj informací o uživatelích. Uživatelské objekty mají standardní třídy `inetOrgPerson`, `organizationalPerson`, `person` a dále vlastní třídu `partyPerson`, ve které jsou atributy neobsažené ve standardních třídách.

.Atributy uživatelských objektů
[options="header",cols="<2,^1,^1,<5"]
|===
| Název
| Četnost
| Unikátní
| Význam atributu

| `cn`
| 1
| {y}
| Primární unikátní identifikátor odpovídající ID na fóru, nebude se nikdy měnit. Keycloak bude v budoucnu generovat nová ID jako vzestupnou řadu.

| `uid`
| 1
| {y}
| Unikátní přihlašovací jméno uživatele, které je možné bezpečně změnit.

| `mail`
| 1
| {y}
| Unikátní email uživatele a alternativní přihlašovací jméno, které je možné bezpečně změnit. Zajištěný kanál pro komunikaci s uživatelem.

| `mobile`
| 0..1
| {y}
| Mobilní číslo uživatele, nepovinné.

| `sn`
| 1
| {n}
| Příjmení uživatele, povinné.

| `givenName`
| 1
| {n}
| Rodné (křestní) jméno uživatele, nepovinné.

| `displayName`
| 1
| {n}
| Kombinace `givenName` a `sn` oddělených mezerou.

| `enabled`
| 1
| {n}
| Stav uživatelského účtu -- aktivní / neaktivní.

| `emailVerified`
| 1
| {n}
| Stav ověření aktuálního emailu uživatele.

| `partyEmail`
| 0..1
| {n}
| Stranický email. Slouží především pro vytvoření aliasu a následnou prezentaci veřejnosti.

| `userPassword`
| 0..1
| {n}
| Zabezpečené heslo registrovaných osob.

| `memberOf`
| 0..n
| {n}
| Členství uživatele ve skupinách, zejména v LDAPovém podstromu `OU=Groups,O=Pirati`.
|===

<<<

==== `OU=Groups,O=Pirati`

V tomto podstromu budou postupně vznikat skupiny dle potřeb organizace. Objekty skupin jsou především standardního typu `groupOfUniqueNames` a vlastního typu `partyGroup`. Zatím nejsou známé žádné rozšiřující atributy.


.Atributy objektů uživatelských skupin
[options="header",cols="<2,^1,^1,<5"]
|===
| Název
| Četnost
| Unikátní
| Význam atributu

| `cn`
| 1
| {y}
| Unikátní identifikátor skupiny.

| `description`
| 0..1
| {n}
| Podrobný popis skupiny.

| `uniqueMember`
| 0..n
| {n}
| Seznam členů dané skupiny.
|===

Konzistenci vazby mezi uživateli a skupinami zajišťuje LDAP, ale vzhledem k tomu, že by se ani jedno z `CN` nemělo měnit, stačí jenom automatické propisování atributů `member` a `uniqueMember`.

NOTE: Potenciálně můžeme využít možnost členství skupin ve skupinách, ale případné výhody či nevýhody tohoto řešení vyžadují analýzu a další diskuzi.


==== `OU=Systems,O=Pirati`

V tomto podstromu jsou především objekty standardních typů `applicationProcess` a `simpleSecurityObject`. Tyto objekty slouží pro přihlašování systémových účtů, které mají omezený přístup k ostatním objektům a jejich atributům.

.Atributy objektů klientských systémů
[options="header",cols="<2,^1,^1,<5"]
|===
| Název
| Četnost
| Unikátní
| Význam atributu

| `cn`
| 1
| {y}
| Unikátní přihlašovací jméno služby.

| `userPassword`
| 1
| {n}
| Zabezpečené heslo pro přihlašování.

| `description`
| 0..1
| {n}
| Případný popis přistupující služby.
|===


<<<

== Migrace na nový systém identit

=== Migrace primárního zdroje identit

. Je nasazen LDAP s takovým způsobem ukládání hesel, který je kompatibilní s PirateID.

. Nad LDAPem je zprovozněn Keycloak ve stavu, který umožňuje registraci nových uživatelů a který respektuje výše uvedené schéma LDAPu.

. Uživatelské účty z fóra jsou jednorázově přesunuty z DB do LDAPu a na fóru je změněn způsob ověřování uživatelů tak, aby k němu docházelo nově pouze prostřednictvím SSO. Tento přechod je proveden s výpadkem fóra tak, aby nedošlo k odchylce v přenášených datech.

. Je nasazen skript, který (v souladu s koncepcí výše) replikuje účty a hesla z LDAPu do databáze fóra pro udržení kompatibility s PirateID.

. Veškeré aplikace, které nyní používají PirateID jsou postupně přenastaveny tak, aby využívaly Keycloak.

. PirateID je odstaveno, již není potřeba. Také je zrušena replikace hesel do databáze fóra a tam uložená hesla jsou smazána.


=== Implementace stranické logiky

. Je nasazen skript, který replikuje skupiny z fóra do LDAPu dle aktuálních potřeb. V této fázi není cílem řídit kvalitu struktury skupin. Skript se může průběžně měnit. Snažíme se zjistit reálné požadavky provozu.

. Koncové systémy, které již pracují s novým systémem LDAP/SSO využívají skupiny z fóra k řízení oprávnění uživatelů. Pokud potřebují informaci o skupinách i pro jiné účely než je kontrole oprávnění aktuálně přihlášeného uživatele, je souběžně nasazována replikace dat z LDAPu do místních databází.

. Probíhá implementace systémů Nalodění a People.

. Systém People umožňuje správu skupin oddělených od skupin z fóra a probíhá migrace řízení oprávnění směrem ke skupinám nastaveným tímto systémem.

. Je zrušena replikace skupin z fóra do LDAPu, již není potřeba. Je nahrazena replikací v opačném směru -- systém People řídí příslušnost osob ke skupinám na fóru.


<<<

== Vlna

WARNING: Tato sekce není úplná.

Vlna má za cíl umožnit odesílání hromadných emailů a později textových zpráv při dodržení podmínek daných zákonem a tvořit tak kontaktní kanál s aktuálními adresami a čísly pro stranické funkcionáře a koordinátory dobrovolníků.


.Závislosti mezi komponentami (Vlna)
====
[plantuml,align="center"]
....
@startuml

database LDAP
component "Keycloak" as sso

package Vlna {
  database DB

  component httpd
  component "Webová aplikace" as web
  component "Replikace" as rep
}

cloud {
  component "mailgun.com" as mailgun
  mailgun <.r. web
}

sso .d.> LDAP

httpd .r.> sso
httpd .d.> web

web .d.> DB
DB <.r. rep
rep .r.> LDAP
@enduml
....
====


=== Identity

. Z ústředního LDAPu se do interní databáze Vlny přenáší:

.. Názvy a identifikátory všech skupin
.. Jména, emaily, čísla mobilů a příslušnosti ke skupinám všech osob

. Pro vybrané skupiny se v databázi Vlny zakládají i odpovídající kanály.

. Kromě běžného přihlášení přes SSO je možné se přihlásit i odkazem v přijatém emailu tak, aby mohl své odběry spravovat i uživatel, který nemá v LDAPu žádné heslo.


=== Databáze

. Vlna využívá určenou PostgreSQL databázi.

. V databázi jsou uloženy:

.. Replikované údaje z LDAPu
.. Preference uživatelů, tedy zejména nastavení odběrů
.. Rozpracovaná a historická vysílání
.. Statistické informace z Mailgunu


// vim:set spell spelllang=cs,en:
